-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "" SALT '' HASH '' ADMIN;           
CREATE SEQUENCE "PUBLIC"."CATEGORY_SEQ" START WITH 1 INCREMENT BY 50;         
CREATE SEQUENCE "PUBLIC"."ORDERS_SEQ" START WITH 1 INCREMENT BY 50;           
CREATE SEQUENCE "PUBLIC"."PAYMENTMETHOD_SEQ" START WITH 1 INCREMENT BY 50;    
CREATE SEQUENCE "PUBLIC"."REVIEW_SEQ" START WITH 1 INCREMENT BY 50;           
CREATE SEQUENCE "PUBLIC"."SHOE_SEQ" START WITH 1 INCREMENT BY 50;             
CREATE SEQUENCE "PUBLIC"."USERS_SEQ" START WITH 1 INCREMENT BY 50;            
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_CATEGORY"(
    "CATEGORY_ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "NAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."HTE_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_CATEGORY;            
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ORDERS"(
    "ORDER_ID" INTEGER,
    "PAYMENT_ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "USER_ID" INTEGER,
    "PRICE" FLOAT(53),
    "STATUS" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."HTE_ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ORDERS;              
CREATE CACHED TABLE "PUBLIC"."CATEGORY"(
    "CATEGORY_ID" INTEGER NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
); 
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31" PRIMARY KEY("CATEGORY_ID");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;
CREATE CACHED TABLE "PUBLIC"."ORDER_SHOES"(
    "ORDER_ID" INTEGER NOT NULL,
    "SHOE_ID" BIGINT NOT NULL
);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_SHOES;             
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_PAYMENTMETHOD"(
    "PAYMENT_ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "METHOD" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."HTE_PAYMENTMETHOD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("RN_");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_PAYMENTMETHOD;       
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ORDER_ID" INTEGER NOT NULL,
    "PAYMENT_ID" INTEGER NOT NULL,
    "PRICE" FLOAT(53) NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "STATUS" CHARACTER VARYING(255) NOT NULL
);              
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B7" PRIMARY KEY("ORDER_ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
CREATE CACHED TABLE "PUBLIC"."PAYMENTMETHOD"(
    "PAYMENT_ID" INTEGER NOT NULL,
    "METHOD" CHARACTER VARYING(255) NOT NULL
);           
ALTER TABLE "PUBLIC"."PAYMENTMETHOD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" PRIMARY KEY("PAYMENT_ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PAYMENTMETHOD;           
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_REVIEW"(
    "REVIEW" INTEGER,
    "REVIEW_ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "USER_ID" INTEGER,
    "SHOE_ID" BIGINT
);          
ALTER TABLE "PUBLIC"."HTE_REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8C" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_REVIEW;              
CREATE CACHED TABLE "PUBLIC"."REVIEW"(
    "REVIEW" INTEGER,
    "REVIEW_ID" INTEGER NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "SHOE_ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8F" PRIMARY KEY("REVIEW_ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REVIEW;  
CREATE CACHED TABLE "PUBLIC"."SHOE"(
    "CATEGORY_ID" INTEGER,
    "PRICE" FLOAT(53) NOT NULL,
    "SIZE" INTEGER NOT NULL,
    "STOCK" INTEGER NOT NULL,
    "SHOE_ID" BIGINT NOT NULL,
    "SHOE_NAME" CHARACTER VARYING(255) NOT NULL
);           
ALTER TABLE "PUBLIC"."SHOE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("SHOE_ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SHOE;    
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_USERS"(
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "USERNAME" CHARACTER VARYING(10),
    "PASSWORD" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."HTE_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("RN_");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_USERS;               
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" INTEGER NOT NULL,
    "USERNAME" CHARACTER VARYING(10) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL
);         
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_SHOE"(
    "CATEGORY_ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "SIZE" INTEGER,
    "STOCK" INTEGER,
    "PRICE" FLOAT(53),
    "SHOE_ID" BIGINT,
    "SHOE_NAME" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."HTE_SHOE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("RN_");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_SHOE;
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B" UNIQUE NULLS DISTINCT ("PAYMENT_ID");   
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" UNIQUE NULLS DISTINCT ("NAME");        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("USERNAME");       
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK32QL8UBNTJ5UH44PH9659TIIH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_SHOES" ADD CONSTRAINT "PUBLIC"."FKEJC43JHVB80QB180DV77PIBI2" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ORDER_ID") NOCHECK;            
ALTER TABLE "PUBLIC"."SHOE" ADD CONSTRAINT "PUBLIC"."FK2FTJJ059SBE8DWAHXG7JS0FNG" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("CATEGORY_ID") NOCHECK;           
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK8NWPSO8H9IW01WC2X03KV6IE6" FOREIGN KEY("PAYMENT_ID") REFERENCES "PUBLIC"."PAYMENTMETHOD"("PAYMENT_ID") NOCHECK;      
ALTER TABLE "PUBLIC"."ORDER_SHOES" ADD CONSTRAINT "PUBLIC"."FK5HKLPUFAFYWYV5QFHW2BYSI8" FOREIGN KEY("SHOE_ID") REFERENCES "PUBLIC"."SHOE"("SHOE_ID") NOCHECK; 
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FK6CPW2NLKLBLPVC7HYT7KO6V3E" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FK8749PH1C0QAAD2X8CNIA04H3" FOREIGN KEY("SHOE_ID") REFERENCES "PUBLIC"."SHOE"("SHOE_ID") NOCHECK;      
